name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: 'windows-2016'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        DOTNET_NOLOGO: true
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      id: build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      id: test
      run: |
        dotnet test --no-restore --no-build --verbosity normal -c Release
        echo ::set-output name=exit_code::$?
      
    - name: Publish
      id: publish
      if: steps.test.outputs.exit_code == 0
      run: |
        cd scripts
        ./publish.ps1
        echo ::set-output name=exit_code::$?
      shell: 
        pwsh
        
    - name: Upload App Publish Artifact
      if: steps.publish.outputs.exit_code == 0
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}\src\App\bin\Publish\
        
    - name: Upload SerialPortListener Publish Artifact
      if: steps.publish.outputs.exit_code == 0
      uses: actions/upload-artifact@v2
      with:
        name: SerialPortListener
        path: ${{ github.workspace }}\src\SerialPortListener\bin\Publish\
        
    - name: Create Release
      id: release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Active work will be done to eliminate bugs and release a full-fledged release as soon as possible
        draft: false
        prerelease: false
