name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: 'windows-2016'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        DOTNET_NOLOGO: true
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      id: build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      id: test
      run: |
        dotnet test --no-restore --no-build --verbosity normal -c Release
        echo ::set-output name=exit_code::$?
      
    - name: Publish
      id: publish
      if: steps.test.outputs.exit_code == 0
      run: |
        cd scripts
        ./publish.ps1
        echo ::set-output name=exit_code::$?
      shell: 
        pwsh
        
    - name: Upload App Publish Artifact
      id: upload_app
      if: steps.publish.outputs.exit_code == 0
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}\src\App\bin\Publish\
        
    - name: Upload SerialPortListener Publish Artifact
      id: upload_serial
      if: steps.publish.outputs.exit_code == 0
      uses: actions/upload-artifact@v2
      with:
        name: SerialPortListener
        path: ${{ github.workspace }}\src\SerialPortListener\bin\Publish\
        
    - name: Bump version and push tag
      id: tag_version
      if: steps.publish.outputs.exit_code == 0
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create a GitHub release
      id: create_release
      if: steps.publish.outputs.exit_code == 0
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        
    - name: Upload App Release Asset
      if: steps.publish.outputs.exit_code == 0
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ github.workspace }}\src\App\bin\Publish\
        asset_name: App.zip
        asset_content_type: application/zip

#     - name: Upload SerialPortListener Release Asset
#       if: steps.publish.outputs.exit_code == 0
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ${{ github.workspace }}\src\SerialPortListener\bin\Publish\
#         asset_name: SerialPortListener.zip
#         asset_content_type: application/zip